name: sh-check
on:
  - pull_request
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -s # arguments to shfmt.
        with:
          sh_checker_comment: true
